name: Trivi Scan
on:
  workflow_call: 

jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
          - name: Print Hello World
            run: |
              echo "Hello World!"          

    actions:
      name: actions 
      uses: rodolfourb/pipe-template/.github/workflows/actions/action.yml@main
