name: Trivi Scan
on:
    workflow_call: 

jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
          - name: Print Hello World
            run: |
              echo "Hello World!"          